apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: eventing-demo-git-resource
  namespace: gfandada
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/gfandada/eventing-demo
