apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventing-demo
  namespace: gfandada
spec:
  template:
    metadata:
      labels:
        app: eventing-demo
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: __IMAGE__
          env:
            - name: TARGET
              value: "gfandada@gmail.com"
      imagePullSecrets:
        - name: image-pull